services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quizz-client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
      NEXT_PUBLIC_WS_URL: http://localhost:4000/quiz
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    extra_hosts:
      - "host.docker.internal:host-gateway"
