FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY tsconfig.build.json ./

EXPOSE 4000

CMD ["sh", "-c", "npm run prisma:generate && npm run prisma:migrate && npm run db:seed && npm run start:dev"]
